### ISSUE TITLE
how to hide current display to show terminal text message ?

### ISSUE THREAD

**Issue by trngaje** [OtherCrashOverride/libgo2#1]
I am applying attract mode using libgo2 library.
Your library is a very good library to use.
but I have a problem.
The linux terminal message cannot be viewed because it does not terminate frontend app (attractmode) when I run game rom.
I am referring to the ES and the retrorun code.
Your ES works well. When you run a rom, the screen is hidden moderately.
I don't know how to approach it.
No function in libgo2 can erase the screen. Cannot show/hide a separate window because x11 is not in use.
If you have any opinion, please reply.

**Comment by OtherCrashOverride** [comment]
ES (or any application) must close the display before any other application can use it without conflict.

**Comment by trngaje** [comment]
thanks for your response
