### ISSUE TITLE
When using this lib with retrorun, libretro flycast

### ISSUE THREAD

**Issue by Langerz82** [OtherCrashOverride/libgo2#4]
Hey, when using this library with retrorun, flycast I noticed by default the left x-axis, and y-axis values are inverted for a Rockchip based handheld device. I don't know if it's the case with other emulator cores.

I've had to apply the following patch to retrorun after the call to your libraries method: go2_input_state_thumbstick_get
https://github.com/Langerz82/retrorun-go2/commit/c0e1258bcc82f65782c5ec811c78bd86ee867486

I'm not positive it is with all devices, but for my device I have to invert the values in order for it to work properly.

Not sure if a fix is needed for this library or for retrorun-go2 but figured I'd raise it as an issue.

**Comment by Langerz82** [comment]
I performed a jstest with /dev/input/js0, for left axis, and right value is negative and left value is positive. same for right axis.

**Comment by OtherCrashOverride** [comment]
Only the official ODROID devices are supported.  Changes for other hardware can not be accepted since there is no way to verify operation without the specific hardware.
